"""Shared Pydantic schemas for API, planning, and execution contracts."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class AnalyzeRequest(BaseModel):
    """Incoming analysis request."""

    query: str = Field(..., min_length=3, examples=["Why did pipeline velocity drop this week?"])


class EvidenceItem(BaseModel):
    """Structured evidence emitted by the workflow."""

    label: str
    value: Any
    metadata: dict[str, Any] = Field(default_factory=dict)


class TraceEvent(BaseModel):
    """Trace event for user-facing workflow visibility."""

    step: str
    status: Literal["started", "completed", "failed"]
    details: dict[str, Any] = Field(default_factory=dict)


class ErrorItem(BaseModel):
    """Structured error payload kept in state and API responses."""

    step: str
    message: str
    recoverable: bool = True
    details: dict[str, Any] = Field(default_factory=dict)


class ArtifactSummary(BaseModel):
    """Compact artifact summary stored in state and returned to the UI."""

    alias: str
    artifact_type: Literal["table", "scalar", "text", "unknown"] = "unknown"
    row_count: int = 0
    columns: list[str] = Field(default_factory=list)
    preview_rows: list[dict[str, Any]] = Field(default_factory=list)
    summary: dict[str, Any] = Field(default_factory=dict)


class ExecutionStep(BaseModel):
    """Exact executable step generated by Gemini."""

    id: str
    kind: Literal["sql", "pandas"]
    purpose: str
    input_views: list[str] = Field(default_factory=list)
    code: str
    output_alias: str
    expected_output: dict[str, Any] = Field(default_factory=dict)
    success_criteria: list[str] = Field(default_factory=list)
    is_final_step: bool = False


class PlannerDecision(BaseModel):
    """Gemini planner output for one loop iteration."""

    intent: Literal["diagnosis", "comparison", "recommendation"]
    metric: Literal["pipeline_velocity"]
    reasoning_summary: str
    action: Literal["execute_step", "finish"]
    step: ExecutionStep | None = None
    completion_reason: str | None = None


class ExecutedStep(BaseModel):
    """Execution log for one attempted step."""

    id: str
    kind: Literal["sql", "pandas"]
    purpose: str
    code: str
    output_alias: str
    attempt: int
    status: Literal["success", "failed"]
    artifact: ArtifactSummary | None = None
    error: str | None = None


class AnalyzeResponse(BaseModel):
    """Final API response for a completed analysis run."""

    summary: str
    root_cause: str
    recommendation: str
    evidence: list[EvidenceItem]
    trace: list[TraceEvent]
    executed_steps: list[ExecutedStep]
    verified: bool
    errors: list[ErrorItem]


class HealthResponse(BaseModel):
    """Health endpoint response."""

    status: str
    app_name: str


class SampleQuestionsResponse(BaseModel):
    """Sample questions endpoint response."""

    questions: list[str]
